#!/bin/sh
ssh -o StrictHostKeyChecking=no ec2-user@172.31.36.192 <<EOF
    cd ~/Devpractice
    git pull origin main
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install v16.20.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF